# Generated by Django 4.1.2 on 2022-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=45)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('actif', models.BooleanField(default=False)),
                ('dateCreation', models.DateField()),
            ],
        ),
    ]
