# Generated by Django 4.1.2 on 2022-12-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField()),
                ('objet', models.CharField(max_length=260)),
                ('description', models.CharField(max_length=1000)),
                ('dateCreation', models.DateField()),
                ('heureDemande', models.DateTimeField()),
                ('Type', models.CharField(choices=[('MAI', 'Maintenance'), ('RS', 'Reseau'), ('SP', 'Sigaspe'), ('AS', 'Alias'), ('SA', 'Sadina'), ('PK', 'Priska'), ('DN', 'Dian'), ('ST', 'Sita')], max_length=5)),
                ('ministere', models.CharField(choices=[('MF', 'Mfptps'), ('MN', 'Mena'), ('MU', 'Muafh'), ('MJ', 'Mjdh'), ('MA', 'Maf'), ('MS', 'Mshpb'), ('ME', 'Mefp'), ('MTM', 'Mtmusrs'), ('MD', 'Matd'), ('EA', 'Mea'), ('MCA', 'Mccat'), ('MSI', 'Mesri'), ('JAS', 'Msaj'), ('CM', 'Mmc'), ('MCE', 'Memc'), ('CAI', 'Mdica')], max_length=5)),
                ('statut', models.CharField(choices=[('EC', 'Encours'), ('RE', 'Regle'), ('CL', 'Clos'), ('NV', 'Nouveau')], max_length=5)),
            ],
        ),
    ]
