# Generated by Django 4.1.2 on 2022-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='ministere',
            field=models.CharField(choices=[('MF', 'Mfptps'), ('MN', 'Mena'), ('MU', 'Muafh'), ('MJ', 'Mjdh'), ('MA', 'Maf'), ('MS', 'Mshpb'), ('ME', 'Mefp'), ('MTM', 'Mtmusrs'), ('MD', 'Matd'), ('EA', 'Mea'), ('MCA', 'Mccat'), ('MSI', 'Mesri'), ('JAS', 'Msaj'), ('CM', 'Mmc'), ('MCE', 'Memc'), ('CAI', 'Mdica')], max_length=5),
        ),
    ]
